run-name: ${{ github.actor }} New test Release 
on:
  push:
    tags:
      - 'v*'
jobs:
    
  new_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read 
      deployments: write
    steps:

      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}
      - name: tag ?
        run: echo ${{ github.ref_name }}

      - uses: actions/checkout@v4
      - run: echo "apt update image non modifiable"
      - run: ls
      - run: systemd-detect-virt
      - run: env
      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "release.tar.gz"
          bodyFile: "README.md"
          allowUpdates: true

          
